name: bridge_counter
description: A Point calculator for Rubber Bridge.

version: 1.1.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Services
  dependencies:
  google_mobile_ads: ^2.0.1

  # Utils
  url_launcher: ^6.1.5

  # State Management
  provider: ^6.0.3
  intl: ^0.17.0

  # Data Management
  shared_preferences: ^2.0.15

  # Resources
  material_design_icons_flutter: ^5.0.6996

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/es.json
    - assets/translations/fr.json
    - assets/translations/pt.json
