name: bridge_counter
description: Rubber Bridge point counter.

version: 1.2.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Services
  firebase_admob: ^0.9.3+2
  firebase_analytics: ^5.0.11

  # Utils
  url_launcher: ^5.4.10

  # State Management
  provider: ^4.3.3

  # Data Management
  shared_preferences: ^0.5.7

  # Assets
  material_design_icons_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/es.json
    - assets/translations/fr.json
    - assets/translations/pt.json
